### ISSUE TITLE
只能用 Python 调用吗？Shell 脚本能直接调用么？（第一个★

### ISSUE THREAD

**Issue by XIU2** [zaxtyson/LanZouCloud-API#1]
看了下，好像所有操作都需要 Python 才能调用，但是我不懂 Python，我想要直接用 Shell 调用该程序，实现蓝奏云上传文件等操作。
所以说，作者有没有其他方法，或者写个简单的成品也行~

**Comment by zaxtyson** [comment]
建议看看这个 https://github.com/zaxtyson/LanZouCloud-CMD
这个可以在linux和Windows平台下用，你只需安装python3后 执行 `python3 lanzou-cmd.py`即可，当然，你需要先安装rar命令 `sudo apt install rar`

**Comment by XIU2** [comment]
原来作者早就考虑到了！谢啦~
