### ISSUE TITLE
get_file_info_by_url ERROR - 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by extr15** [zaxtyson/LanZouCloud-API#103]
Hi, thanks for your work. It seems `lanzoui` had some modifications.
I got this error `get_file_info_by_url ERROR - 'NoneType' object has no attribute 'group'` when processing a `https://lanzoui.com/` link **with a password** (No error for links without a password).

I spent some time and it was caused by `sign = re.search(r"sign=(\w+?)&", first_page).group(1)`: [this line](https://github.com/zaxtyson/LanZouCloud-API/blob/master/lanzou/api/core.py#L472)
Some content of `first_page` are:
```
var skdklds = 'BmB......';
$.ajax({
	type : 'post',
	url : '/ajaxm.php',
        data : { 'action':'downprocess','sign':skdklds,'p':pwd },
```
So I modified the previous line to `sign = re.search(r"skdklds = '(\w+?)';", first_page).group(1)` and it worked.

I hope this helps and it would be great if you could fix this.

**Comment by NovaShen555** [comment]
need help yet?

**Comment by extr15** [comment]
Thanks, and I have solved it.
