### ISSUE TITLE
文件夹 id 不在html里面了，就在刚刚

### ISSUE THREAD

**Issue by rachpt** [zaxtyson/LanZouCloud-API#12]
:sob: :sob:

好像是加了 task

task  "47"

所有的 post 方法都在这里面
https://pc.woozooo.com/includes/js/comm.js?v7277677

**Comment by zaxtyson** [comment]
😂 要和我们掐个你死我活才罢休

**Comment by zaxtyson** [comment]
O了，修复完成。`get_full_path()` 和 `get_dir_list()` 的数据都官方被放到 task 47 去了，抓网页啥也没有。不知道官方是不是在重构，是的话，接下来可能又几个函数要挂掉。
