### ISSUE TITLE
有些界面 文件名匹配不到

### ISSUE THREAD

**Issue by rachpt** [zaxtyson/LanZouCloud-API#13]
比如 https://www.lanzous.com/iat4bpe  这个

`get_share_file_info`
```python
f_name = re.findall(r'<div style="[^"]+">([^><]*?)</div>', first_page)
if f_name:
    f_name = f_name[0]
else:
    f_name = re.findall(r"var filename = '(.*)';", first_page)[0]
```
这两个都匹配不到，列表解析直接越界  `IndexError: list index out of range`

可以这样改：
```python
f_name = re.findall(r'<div style="[^"]+">([^><]*?)</div>', first_page)
if not f_name:
    f_name = re.findall(r"var filename = '(.*)';", first_page)
if not f_name:
    f_name = re.findall(r'<div class="filethetext" id="[^"]*">(.*?)?</div>', first_page)
f_name = f_name[0] if f_name else ""
```

**Comment by zaxtyson** [comment]
OK，了解，等下看看。
刚刚在弄上传下载的续传，基本上做完了。但是现在下载大文件开始检测流量了，下载文件提示网络异常，但是不针对 UA 和 ip，直接针对用户账号。纯数字验证码，干扰图样不是很多，我在想要不要用 ocr 自动处理，还是加一个回调函数，碰到了交个用户手动处理。
![](https://upload.cc/i1/2020/04/01/j8X5Wy.png)

**Comment by zaxtyson** [comment]
昨天还发现了一些问题，task 47 有时候返回无效数据；`get_move_folders()` 获取全部文件夹时会返回一些网盘和回收站不可见的"幽灵文件夹"，文件移动进去就没了。所以又增加了 `clean_ghost_folders()` 用来清理这些文件夹。等我把验证码解决了再push上来。

**Comment by zaxtyson** [comment]
基本上完成了，已经 push 到 dev 分支

**Comment by rachpt** [comment]
那个 `幽灵文件夹` 其实是 文件夹的 父文件夹 不在了， 或者 直接就是父文件夹id 无效 导致的。
有两种方法得到这样的 `幽灵文件夹`：
  1.  新建文件夹时，指定一个无效的 父文件夹 id，https://github.com/rachpt/lanzou-gui/issues/21#issuecomment-599970343
  2. 删除子文件夹和父文件夹，但是只回复子文件夹，那么子文件夹就是这样的 `幽灵文件夹`。

根本原因是蓝奏云在创建文件夹时不校验 父文件夹是否有效；恢复文件夹时，不能修改文件夹之间的链接关系。

直接使用 folder_id 是可以切换目录进去的

**Comment by zaxtyson** [comment]
对的，所以加了  `clean_ghost_folders()` 来清理这些文件夹，虽然可以获取里面的文件，但是网页端看不到，还是不要让它存在的好。
