### ISSUE TITLE
回收站 增加方法

### ISSUE THREAD

**Issue by rachpt** [zaxtyson/LanZouCloud-API#14]
文件回收站目前的方法都是单个的。
还有几个批量 删除、恢复 的方法，可以加上么？
大概是这个样子：
https://github.com/rachpt/lanzou-gui/blob/e84a1b79a44ea79469b55ed10f3a7588ed17375d/lanzou/api/core.py#L245

https://github.com/rachpt/lanzou-gui/blob/e84a1b79a44ea79469b55ed10f3a7588ed17375d/lanzou/api/core.py#L282

https://github.com/rachpt/lanzou-gui/blob/e84a1b79a44ea79469b55ed10f3a7588ed17375d/lanzou/api/core.py#L301

**Comment by zaxtyson** [comment]
这样 GUI 批量删除的确比较方便，等下就加上。

**Comment by zaxtyson** [comment]
已经加上了，在 dev 分支已经更新
