### ISSUE TITLE
get_durl_by_url获取不了某种分享链接的信息

### ISSUE THREAD

**Issue by blueflagbj** [zaxtyson/LanZouCloud-API#16]
使用get_durl_by_url(share_url, pwd)不能够获取某种分享链接的信息，形如：https://www.lanzous.com/taiguz 这个地址里面就无法获取信息，返回值为6。
但是形如这样的：https://www.lanzous.com/iasuyob 却能够正常获取文件信息。

**Comment by zaxtyson** [comment]
获取信息前会判断 URL 是否有效，错误码 6 表示 `URL_INVALID` 链接无效，看样子蓝奏云的 URL 发生变化了。 https://github.com/zaxtyson/LanZouCloud-API/blob/c1d2c99a2084b22bde300f1fefe0d19c09d209dd/lanzou/api/utils.py#L68
所以被误判了。
`https://www.lanzous.com/taiguz` 这个应该是会员用户分享页面的吧，因为我是普通用户，所以这种情况很少碰到，能否再分享一些文件夹以及设置了提取码的文件和文件夹，方便测试，谢谢~

**Comment by zaxtyson** [comment]
修复已经推到 dev 分支，但是测试可能还不充分，需要更多例子😁

**Comment by blueflagbj** [comment]
https://www.lanzous.com/iaxw5qb
https://www.lanzous.com/iax14zi
https://www.lanzous.com/iasuyob
https://www.lanzous.com/taigu
https://www.lanzous.com/taiguz
https://www.lanzous.com/iaw78li
https://www.lanzous.com/395pk
https://www.lanzous.com/iaufw3a
https://www.lanzous.com/iax14pi
https://www.lanzous.com/xunxianOL
https://www.lanzous.com/shenchuangz
https://www.lanzous.com/iaxqcij
https://www.lanzous.com/1023436
https://www.lanzous.com/iaw8gta
http://www.lanzous.com/iaw8gta
https://www.lanzous.com/iadxkzg
https://www.lanzous.com/ia3z3hi
https://www.lanzous.com/iaw5uhe
https://www.lanzous.com/iaxlb7c
https://www.lanzous.com/2345-3
https://www.lanzous.com/iawl1qf
https://www.lanzous.com/iavj6of
https://www.lanzous.com/iayfcij
https://www.lanzous.com/iaouvch
https://www.lanzous.com/iaw8txc
https://www.lanzous.com/iax14fi
https://www.lanzous.com/iaufccj
https://www.lanzous.com/972pk
https://www.lanzous.com/jfjwhj
这是一些地址，里面有返回值为6的，有返回值为2的，也有正常返回0的，甚至有些是报错的，链接不保证一直有效，请尽快测试

**Comment by zaxtyson** [comment]
问题处理完成，但是这些都是文件，能否再分享两个文件夹呢😀。

**Comment by blueflagbj** [comment]
https://www.lanzous.com/iaxw5qb
https://www.lanzous.com/iaw28gd
https://www.lanzous.com/iaw28cj
https://www.lanzous.com/iayxali
https://www.lanzous.com/iadxvli
https://www.lanzous.com/TZSQ999
https://www.lanzous.com/iaz0jgf
https://www.lanzous.com/ib06ztg
https://www.lanzous.com/xunxianOL
https://www.lanzous.com/shenchuangz
https://www.lanzous.com/ia9mdhg
https://www.lanzous.com/ia9mddc
https://www.lanzous.com/ib0n9oh
https://www.lanzous.com/iaylzlg
https://www.lanzous.com/iaxlb7c
https://www.lanzous.com/ia3z3hi
https://www.lanzous.com/iaxqcij
https://www.lanzous.com/iayx2yd
https://www.lanzous.com/GFZS999
https://www.lanzous.com/b0oglaf
https://www.lanzous.com/i98wseb
https://www.lanzous.com/iazyyjc
https://www.lanzous.com/iaz0j4d
https://www.lanzous.com/iazgwng
https://www.lanzous.com/taigu
https://www.lanzous.com/taiguz
https://www.lanzous.com/iaz0nng
https://www.lanzous.com/iasuyob
https://www.lanzous.com/iawfxsd
https://www.lanzous.com/iadxkzg
https://www.lanzous.com/ib0qzxa
http://www.lanzous.com/ib0qzxa
https://www.lanzous.com/iay9z5i
https://www.lanzous.com/yx0331
https://www.lanzous.com/ia7644b
https://www.lanzous.com/fjie
https://www.lanzous.com/kx987
https://www.lanzous.com/kxwd533
https://www.lanzous.com/iazlhng
https://www.lanzous.com/iaxnpab
https://www.lanzous.com/iaxnp4f
https://www.lanzous.com/i9iwk2b
https://www.lanzous.com/i9iwina
https://www.lanzous.com/iaz3f9c
https://www.lanzous.com/1023436
https://www.lanzous.com/1Nqx3SVr
https://www.lanzous.com/972pk
https://www.lanzous.com/iazispg

这里面https://www.lanzous.com/b0oglaf是文件夹

**Comment by blueflagbj** [comment]
还是有返回值6的情况，不过已经好太多了

**Comment by zaxtyson** [comment]
修复版其实还没push上来，我是想把 VIP文件夹 URL 也解决了再上传 2.4.4 版，VIP 文件 URL 已经不会有问题了

**Comment by zaxtyson** [comment]
看样子VIP用户分享的文件夹和普通用户一样额。
刚刚把 2.4.4 推到了 dev 分支，您可以试一下。

**Comment by blueflagbj** [comment]
在线程中使用，下载的时候，会出现链接development30.baidupan.com 这样的地址 openssl报错，表现链接超时
Traceback (most recent call last):
  File "C:\Users\Administrator.USER-20190402YM\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\Administrator.USER-20190402YM\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "E:\AllByOne\Project\Source\ZhaoSF\ZSF\zsfmm\zsfmm\spiders\PreSvr.py", line 99, in lanzoudown
    code = lzy.down_file_by_url(url)
  File "C:\Users\Administrator.USER-20190402YM\AppData\Local\Programs\Python\Python38\lib\site-packages\lanzou_api-2.4.3-py3.8.egg\lanzou\api\core.py", line 901, in down_file_by_url
  File "C:\Users\Administrator.USER-20190402YM\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\models.py", line 758, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='development30.baidupan.com', port=443): Read timed out.

**Comment by zaxtyson** [comment]
可能是网络不太好，默认设置的超时是 5 秒，需要的话，这个可以改大一点。
https://github.com/zaxtyson/LanZouCloud-API/blob/64d1ff90dd341351e99f514fddccd50b545609f7/lanzou/api/core.py#L43

另外，刚才又提交了一次到 dev，文件大小和时间的问题处理好了
