### ISSUE TITLE
使用时遇到一些问题

### ISSUE THREAD

**Issue by 1300173567** [zaxtyson/LanZouCloud-API#18]
提示检测更新时发生异常，列出文件夹没反应，上传文件也失败，我是纯萌新，cmd都不懂那种。。。。是我哪里操作的不对吗？
注：我没有把软件安在默认位置，没有开管理员权限（看她貌似也不需要）
![image](https://user-images.githubusercontent.com/63437752/78960572-0cf8f180-7b21-11ea-9daf-590de98fa4cc.png)

**Comment by 1300173567** [comment]
补充说明一下，我的蓝奏云账号是新建的，里面没有任何文件，输入ls没有任何反应是正常的吗？上传的文件路径中包含中文。

**Comment by 1300173567** [comment]
> 提示检测更新时偶尔发生异常，列出文件夹没反应，上传文件也失败，我是纯萌新，cmd都不懂那种。。。。是我哪里操作的不对吗？
> 注：我没有把软件安在默认位置，没有开管理员权限（看她貌似也不需要）

**Comment by zaxtyson** [comment]
似乎是一个隐藏 bug😥
