### ISSUE TITLE
登录接口失效了

### ISSUE THREAD

**Issue by AnSiia** [zaxtyson/LanZouCloud-API#21]

**Comment by karsacui** [comment]
+1，正在使用旧版，不敢退出账号

**Comment by zaxtyson** [comment]
可以用cookie登录，之前用web端的接口被干掉了，后来用app端的接口又被干掉了

**Comment by reger007** [comment]
帮我编译个win7 x86版本的可以吗，我自己编译的点击登入后直接奔溃。

**Comment by zaxtyson** [comment]
崩溃的原因应该是，CMD版中使用了 Python3.8 的一些特性，低版本的Python运行会导致语法错误而崩溃。使用Python3.8+试试看~

cookie 的话，登录网页版，查看cookie，找到 `ylogin`、`phpdisk_info`两个字段即可:
![](https://upload.cc/i1/2020/05/23/cCgnke.png)
![](https://upload.cc/i1/2020/05/23/cxEl6n.png)
![](https://upload.cc/i1/2020/05/23/VC6f0o.png)
