### ISSUE TITLE
__

### ISSUE THREAD

**Issue by oiabtt** [zaxtyson/LanZouCloud-API#22]

**Comment by zaxtyson** [comment]
因为我也是白嫖用户，高级功能我也测试不了 ε=ε=ε=(~￣▽￣)~

**Comment by oiabtt** [comment]
我上传后如何获得该文件的id呢？这样我下载的时候才能指定文件下载。

**Comment by zaxtyson** [comment]
看wiki https://github.com/zaxtyson/LanZouCloud-API/wiki/0x06-%E4%B8%8A%E4%BC%A0%E5%92%8C%E4%B8%8B%E8%BD%BD-*#upload_filefile_path-folder_id--callback-uploaded_handler

通过 uploaded_handler 回调函数进一步处理上传的文件
