### ISSUE TITLE
用浏览器可以访问，用此库返回错误码6

### ISSUE THREAD

**Issue by zhbzhbzhbz** [zaxtyson/LanZouCloud-API#26]
非常棒的项目~~~给你们点个赞（都想打赏了哈哈）

然后今天遇到一个特殊的URL：
https://lanzous.com/id4p52j

用浏览器可以访问，
而用`lzy.down_file_by_url('https://lanzous.com/id4p52j')`的时候，返回错误码6，LanZouCloud.URL_INVALID

谢谢您~

**Comment by zaxtyson** [comment]
https://www.lanzous.com/id4p52j 这样就可以了，官方的URL真的是非常的魔性，每隔一段时间就要整点花样。

**Comment by zaxtyson** [comment]
已经修复了

**Comment by zhbzhbzhbz** [comment]
> https://www.lanzous.com/id4p52j 这样就可以了，官方的URL真的是非常的魔性，每隔一段时间就要整点花样。
> 其实子域名没有什么用，https://666666.lanzous.com/id4p52j 也行(￣▽￣*)b

哈哈哈哈哈原来如此！！感谢~~
