### ISSUE TITLE
不知道down_file_by_url方便把返回值改成(code, filename)的形式么~

### ISSUE THREAD

**Issue by zhbzhbzhbz** [zaxtyson/LanZouCloud-API#27]
目前如果想在down_file_by_url()中获得文件名，需要在callback里获取，但是那样的话回调函数又会被每4KB触发一次；
如果不获取，又不知道下载的文件名以便后续处理。
不知道是否方便改成元组的形式，把文件名放在后面？

**Comment by zaxtyson** [comment]
API设计的时候就是这样的，知名见义，功能尽可能简单专一，不然调用的时候会很混乱的。

**Comment by zhbzhbzhbz** [comment]
> API设计的时候就是这样的，知名见义，功能尽可能简单专一，不然调用的时候会很混乱的。

好的谢谢，了解了~（不知道Python里有没有能把callback变成链式调用或者同步调用的函数）

**Comment by zhbzhbzhbz** [comment]
> API设计的时候就是这样的，知名见义，功能尽可能简单专一，不然调用的时候会很混乱的。

我又想了下，很多的下载库，比如js里的jQuery或者android里的asynctask，除了有“下载中”的回调，还会有结束时的回调，不然的话，现在想取到下载的文件名只能把callback里获得的文件名，放到set里，会比较麻烦

**Comment by zaxtyson** [comment]
那个 callback 本来是为了显示进度设置的，只要文件名可以用 `get_durl_by_url()` 或者 `get_file_info_by_url()`（；´д｀) 就是多调用了一次，代价不是很大。或者你可以fork改一下源码，给 `down_file_by_url()` 再加一个回调
https://github.com/zaxtyson/LanZouCloud-API/blob/05131150ccf3061cc79109ace47f9bb05ae399dd/lanzou/api/core.py#L949

`info.name` 就是文件名，不过感觉回调太多了也不好😅

**Comment by zhbzhbzhbz** [comment]
> 那个 callback 本来是为了显示进度设置的，只要文件名可以用 `get_durl_by_url()` 或者 `get_file_info_by_url()`（；´д｀) 就是多调用了一次，代价不是很大。或者你可以fork改一下源码，给 `down_file_by_url()` 再加一个回调
> https://github.com/zaxtyson/LanZouCloud-API/blob/05131150ccf3061cc79109ace47f9bb05ae399dd/lanzou/api/core.py#L949
> 
> `info.name` 就是文件名，不过感觉回调太多了也不好😅

哦哦谢谢~原来还有这个API。
不过我看了下，是需要先判断url类别然后调用您的API，然后如果是文件夹的话，就只能用“get_folder_info_by_url”来获取文件名了对吧？
以及，您觉得这样每次下载都多一次网络访问的话，会增加弹出验证码的概率么？

**Comment by zaxtyson** [comment]
不会，验证码只在下载 `dwg` `iso` 这些文件时出现，蓝奏云官方宣传是不存在验证码的，主页写着 `"来这里，下载无限制，无验证码，畅快淋漓尽致！"`，不知道这特定文件弹验证码是什么意思😅。

**Comment by zhbzhbzhbz** [comment]
> 不会，验证码只在下载 `dwg` `iso` 这些文件时出现，蓝奏云官方宣传是不存在验证码的，主页写着 `"来这里，下载无限制，无验证码，畅快淋漓尽致！"`，不知道这特定文件弹验证码是什么意思😅。

哦哦~原来如此
您有打赏码不？可以贴一个

**Comment by zaxtyson** [comment]
开源项目，全凭热情，无需捐赠😘

**Comment by zhbzhbzhbz** [comment]
@zaxtyson 今天测试了下，以一个16M的文件为例：https://www.lanzoux.com/iRGL1em4prc
1）用回调来获取文件名，即
```
filename_set = set() # 去重
def progress_callback(filename, total_size, now_size):
            if total_size == now_size: # 当总大小=
                filename_set.add(filename)
lzy.down_file_by_url(url, callback=progress_callback)
```
额外开销只有0.001秒
附额外开销测试方式：
```
for i in range(0, 17256448, 4096):
    progress_callback("", 17252352, i)
```
2）用`get_file_info_by_url()`获取文件名，在我的网络情况下，执行一次平均0.9秒

还是上面的方法好一点~

**Comment by zaxtyson** [comment]
获取文件信息的开销的确实是比较大的（尤其是网络不好的情况），下载函数里面首先会调用一次get_file_info_by_url()，因为要获取解析直链，文件信息可以在下载开始前得到。如果真的很在意时间开销，还是加一个回调好些。这两天在乡下，回来再整吧。😄

**Comment by zhbzhbzhbz** [comment]
嗯嗯，这个不重要，反正变通的方法很多


| |
zhbzhbzhbz199102
|
|
zhbzhbzhbz199102@163.com
|
签名由网易邮箱大师定制
在2020年7月20日 08:10，ZaxTyson<notifications@github.com> 写道：

获取文件信息的开销的确实是比较大的（尤其是网络不好的情况），下载函数里面首先会调用一次get_file_info_by_url()，因为要获取解析直链，文件信息可以在下载开始前得到。如果真的很在意时间开销，还是加一个回调好些。这两天在乡下，回来再整吧。😄

**Comment by zaxtyson** [comment]
那就不改喽~主要是怕api接口变化影响其它用户。

`down_file_by_url(share_url, pwd='', save_path='./Download', callback=None)`

`down_dir_by_url(share_url, dir_pwd='', save_path='./Download', *, callback=None, mkdir=True,
                        failed_callback=None)`

具有多个回调函数的方法，都是强制使用关键字参数，但是`down_file_by_url`这种就没有，有些人可能直接给的位置参数，改动接口可能影响一部分人(ಥ _ ಥ)。
