### ISSUE TITLE
又发现了新的url模式

### ISSUE THREAD

**Issue by zhbzhbzhbz** [zaxtyson/LanZouCloud-API#28]
1）https://www.lanzoux.com/iRGL1em4prc 网址里有大写字母，因此后面的部分需要加A-Z
2）（我自己弄的）https://hb-az.lanzous.com/izijcenly5c 三级域名部分有连字符- 注：亲自改了下个性域名，果然跟url规范一样，只允许数字、字母和连字符
3）还有一个可以改善的地方~
比如有这样一个长字符串 `https://habo.qq.com/file/showdetail?pk=ADcGYl1sB24IOVs%2BU2M界面截图:协yi：安卓转PC功能就简单说下吧关闭真锁：拖进去的格式必须是账号-本帖隐藏的内容https://www.lanzoux.com/iRGL1em4prc`，
如果正则表达式里的**三级域名**部分（比如www）用现在的`.*?`而不是`[a-zA-Z0-9-]*?`的话，会导致上面一大长串都被匹配到，而不仅匹配到结尾的URL，哪怕用了非贪婪模式也是如此。

综上三点，建议 base_pat 改成`https?://[a-zA-Z0-9-]*?\.?lanzou[six].com/.+`，
user_pat 改成 `https?://[a-zA-Z0-9-]*?\.?lanzou[six].com/i[a-zA-Z0-9]{5,}/?`，文件夹同理
https://github.com/zaxtyson/LanZouCloud-API/blob/3bd44f8b8a6c496a7aa6d196e14badccc87e3997/lanzou/api/utils.py#L77
https://github.com/zaxtyson/LanZouCloud-API/blob/3bd44f8b8a6c496a7aa6d196e14badccc87e3997/lanzou/api/utils.py#L95

**Comment by zaxtyson** [comment]
😁这两天在乡下，回来就改。
官方真是喜欢搞事呢( 0 x 0 )
URL规则已经变了n次了
