### ISSUE TITLE
生成requirements.txt时有两个lanzou库

### ISSUE THREAD

**Issue by zhbzhbzhbz** [zaxtyson/LanZouCloud-API#29]
在我使用pipreqs . --encoding=utf8 --force智能地生成requirements.txt的时候，别的库都正常，但是lanzou相关的居然有两个：
```
lanzou_api==2.5.3
lanzou==1.0.0
```
而我在代码里也没用到lanzou这个库，不知道是否保留一个就好了，还是是历史遗留（兼容）问题~

**Comment by zaxtyson** [comment]
有一个叫`lanzou`的库，是我很久之前发布到pypi的，后来改名叫`lanzou-api`了，现在一直在维护的就是这个

**Comment by zaxtyson** [comment]
只用了下面两个库
```
requests==2.23.0
requests-toolbelt==0.9.1
```

**Comment by zhbzhbzhbz** [comment]
> 只用了下面两个库
> 
> ```
> requests==2.23.0
> requests-toolbelt==0.9.1
> ```
> 
> 可以直接 `pip install lanzou-api` 会自动安装好依赖的

嗯嗯这个我知道，因为我的项目里不只用了lanzou-api嘛~就找了个可以自动生成requirements.txt的pipreq库。我刚才也看了源码里确实没有依赖lanzou，但是不知道为啥这个库会错误地把lanzou1.0.0这个库也加进去，我再研究研究

**Comment by zaxtyson** [comment]
pipreqs 好像是分析import的库，然后去 pypi 上面找，就把我那个古老的库给找进来了
还是用虚拟环境然后 `pip freeze`来的干净
