### ISSUE TITLE
可以 附带返回文件夹 是否有密码与描述吗？

### ISSUE THREAD

**Issue by rachpt** [zaxtyson/LanZouCloud-API#3]
get_dir_list  只返回 文件夹的 id，其实文件夹是否有密码以及部分描述 也可以通过
`self._mydisk_url + '?item=files&action=index&folder_node=1&folder_id=' + str(folder_id)`
这个链接获得。
`style="display:initial` 表示有密码，文件夹描述在末尾位置 `<font color="#BBBBBB">[这里是描述]</font></div>`
要是`get_dir_list`，`get_file_list2`能返回的dict值是列表就好了。这样就可以获得更多的信息。

```py
def get_dir_list(self, folder_id=-1):
    """获取子文件夹列表"""
    folder_list = {}
    try:
        url = self._mydisk_url + '?item=files&action=index&folder_node=1&folder_id=' + str(folder_id)
        pattern = r'&nbsp;(.+?)</a>&nbsp;.+folkey\((.+?)\).*(style="display:initial")?.*>(.*)?</font>'
        for k, v, have_key, desc in re.findall(pattern, self._session.get(url).text):
            have_key = True if have_key else False
            desc = desc[1:-1] if desc else ''
            folder_list[k.replace('&amp;', '&')] = [int(v), have_key, desc]  # 文件夹名 : [id, key, desc]
        return folder_list
    except requests.RequestException:
        return {}
```

**Comment by zaxtyson** [comment]
文件夹“是否有密码”以及“文件描述”的确应该加入，只是 api 接口命名可能要变化一下了。一个接口返回详细信息，另一个返回 id 列表。获取密码要产生一个post，所以当时丢到 `get_share_info()`里面去了。

**Comment by zaxtyson** [comment]
已更新，api 接口发生细微变化：https://github.com/zaxtyson/LanZouCloud-API/wiki/API-%E6%96%87%E6%A1%A3#get_dir_listfolder_id 😁 CMD明天再弄
