### ISSUE TITLE
pc.woozooo.com未找到phpdisk_info

### ISSUE THREAD

**Issue by mcy567** [zaxtyson/LanZouCloud-API#30]
![image](https://user-images.githubusercontent.com/22673808/88244331-179d5800-ccc6-11ea-8749-256e8210aa98.png)

如图，请问这种要怎么处理

**Comment by mcy567** [comment]
![image](https://user-images.githubusercontent.com/22673808/88244963-f89fc580-ccc7-11ea-903d-45c0aa417cd5.png)
![image](https://user-images.githubusercontent.com/22673808/88245026-2e44ae80-ccc8-11ea-9f8c-eb4d9fdfc081.png)
顺便一提，Python3.6好像不支持 f"{xxx=}" 这种写法，要不要考虑用比较常见的写法格式化字符串，这样能支持更多的Python版本号 : )

**Comment by zaxtyson** [comment]
Cookie 可以在URL边上的🔒那里看到，或者看 `mydisk.php`的cookie
![](https://upload.cc/i1/2020/07/23/XdrPo1.png)

 [f-strings](https://docs.python.org/3.6/whatsnew/3.6.html#whatsnew36-pep498)是 python3.6开始支持的，但是 [f-strings debug](https://bugs.python.org/issue36817) 是 python 3.8.0开始支持的，当时也没考虑到，CMD版还用了海象运算符（语法糖谁不喜欢呢）。linux上面自带的一般是低版本的 python3.6，所以说还是建议上新版，毕竟python3.9呼之欲出，3.10也正在dev中（＞人＜；）

**Comment by mcy567** [comment]
好的，cookie已找到，谢谢！版本的问题 我自己再想想好了~
