### ISSUE TITLE
分享链接的主机名由www改成了wws

### ISSUE THREAD

**Issue by mcy567** [zaxtyson/LanZouCloud-API#31]
![image](https://user-images.githubusercontent.com/22673808/88278040-50641e00-cd14-11ea-8952-401831f457b4.png)
如图，刚刚在获取下载直链的时候怎么都不行，观察了下发下现在已经不是www了。
![image](https://user-images.githubusercontent.com/22673808/88278179-91f4c900-cd14-11ea-8a27-42d5e926022d.png)
上面这个改成了wws就好了

**Comment by zaxtyson** [comment]
蓝奏云可以自定义域名（有时候甚至都没有段），但是这个东西没什么用，`www` 和 `wws` 和 `1234`都是一样的效果，API是可以处理的

**Comment by mcy567** [comment]
![image](https://user-images.githubusercontent.com/22673808/88302698-bc587d80-cd38-11ea-9e12-757dfbd17033.png)
我看到你这边有个拼接的操作：https://www.lanzous.com/ + fn?XXXX
如果用www的域名就会进入到条件语句里面，我直接访问url是404，但是如果改成wws就正常了。
这里面没有什么问题吗？

**Comment by mcy567** [comment]
![Uploading image.png…]()
我想我应该找到原因了。。

**Comment by zaxtyson** [comment]
哈哈，解决了就太好了，不然我又有活干了(￣▽￣)"
