### ISSUE TITLE
遇到了不是iso、dmg也让验证的情况

### ISSUE THREAD

**Issue by zhbzhbzhbz** [zaxtyson/LanZouCloud-API#32]
https://cuntu.lanzous.com/i91dJenk2wb 在访问这个url的时候，提示点击验证，如图。附源代码~
<img width="224" alt="1" src="https://user-images.githubusercontent.com/4599992/88286373-3978f800-cd23-11ea-886e-583058a02424.png">
<img width="325" alt="2" src="https://user-images.githubusercontent.com/4599992/88286378-3b42bb80-cd23-11ea-9d9a-ef587a13df6b.png">
<img width="488" alt="3" src="https://user-images.githubusercontent.com/4599992/88286381-3c73e880-cd23-11ea-99b6-87911e029210.png">
[source.txt](https://github.com/zaxtyson/LanZouCloud-API/files/4965874/source.txt)

**Comment by zaxtyson** [comment]
我这边下载没出现验证，不过 iso 文件直接炸出验证页面 https://zaxtyson.lanzous.com/iuGg8ex8bja

他们果然实现了“无验证码”的承诺，这回连验证码都没了，直接换点击验证了😂

**Comment by zhbzhbzhbz** [comment]
> 我这边下载没出现验证，不过 iso 文件直接炸出验证页面 https://zaxtyson.lanzous.com/iuGg8ex8bja
> 
> 他们果然实现了“无验证码”的承诺，这回连验证码都没了，直接换点击验证了😂

嗯嗯，我在浏览器上会弹，但是用您的库就可以下~哈哈

**Comment by zaxtyson** [comment]
之前的是英文和数字验证码，现在是点击式的了，api 处理验证码的机制得跟着改了，还在折腾中

**Comment by zhbzhbzhbz** [comment]
> 之前的是英文和数字验证码，现在是点击式的了，api 处理验证码的机制得跟着改了，还在折腾中

辛苦了orz，不过单纯判断好像容易点，验证码从展示到点击到结束都是一页简单的html

**Comment by zaxtyson** [comment]
已经解决了😁，点击式的比验证码好解决些，以前的策略是遇到验证码时交给用户手动识别，现在可以自动完成了。
不过遇到验证需要等待2s才能拿到直链数据，调用的开销稍微大一点。

**Comment by zaxtyson** [comment]
改好了，试试 [dev](https://github.com/zaxtyson/LanZouCloud-API/tree/dev)，看看下载验证还有没有问题，没问题就推到 master 分支了

**Comment by zhbzhbzhbz** [comment]
> 改好了，试试 [dev](https://github.com/zaxtyson/LanZouCloud-API/tree/dev)，看看下载验证还有没有问题，没问题就推到 master 分支了😁

您试着可以就行~哈哈
