### ISSUE TITLE
文件夹链接判断是否打错了？

### ISSUE THREAD

**Issue by rachpt** [zaxtyson/LanZouCloud-API#33]
https://github.com/zaxtyson/LanZouCloud-API/blob/ce2654f3dbf13f8b14dc907719a45e8837957fcd/lanzou/api/utils.py#L95

看改动，文件和文件夹两处都是 `...com/i[...`，应该是替换错了吧？

同时，这样的链接也是合法的：
http://汉字.hh.s--s.dd.lanzous.com/b0f14h1od
http://a--.lanzous.com/b0f14h1od
非法：
http://--.lanzous.com/b0f14h1od
<pre>
'https?://(\w[-\w]*\.)?lanzou[six].com/i[a-zA-Z0-9]{7,}/?'
</pre>
`\w` 可以匹配到汉字

**Comment by zaxtyson** [comment]
文件夹那里的确是手误😅

三级域那个，按照官方的要求是 数字、字母、连字符，且不能以连字符开头和结尾

![](https://upload.cc/i1/2020/07/25/MFv0nj.png)

理论上不会出现汉字的情况，除非用户手动加上去。毕竟整个三级域都没什么意义，甚至可有可无🤪。
