### ISSUE TITLE
如何打包

### ISSUE THREAD

**Issue by XM12G** [zaxtyson/LanZouCloud-API#34]
我用pyinstaller打包后，其他人无法正常使用
主要使用下载dir这个，别人用的时候直接闪退，也不会创建Download文件夹

**Comment by zaxtyson** [comment]
下载目录出问题是因为 https://github.com/zaxtyson/LanZouCloud-API/issues/33#issue-665502094 现在已经修复了
api 是封装好的，只要 `pip install lanzou-api`  即可

**Comment by XM12G** [comment]
是报这个语法错：
![QQ图片20200726001156](https://user-images.githubusercontent.com/35884945/88461273-bbf4e980-ced4-11ea-9271-cc86bcab7afc.png)

**Comment by zaxtyson** [comment]
能贴一下代码嘛😀

**Comment by XM12G** [comment]
```
from lanzou.api import LanZouCloud
def show_progress(file_name, total_size, now_size):
    """显示进度的回调函数"""
    percent = now_size / total_size
    bar_len = 40  # 进度条长总度
    bar_str = '>' * round(bar_len * percent) + '=' * round(bar_len * (1 - percent))
    print('\r{:.2f}%\t[{}] {:.1f}/{:.1f}MB | {} '.format(
    percent * 100, bar_str, now_size / 1048576, total_size / 1048576, file_name), end='')
    if total_size == now_size:
        print('')  # 下载完成换行
# ToDo 联网功能
print("已开始下载TAT2.7，下载文件存储在Download文件夹内")
lzy = LanZouCloud()
code = lzy.down_dir_by_url("https://wwa.lanzous.com/b05ahfwhc","","./Download",callback=show_progress)
if code == LanZouCloud.SUCCESS:
    print("下载完成")
else:
    print("遭遇错误，错误码：",code)

input()
```

**Comment by zaxtyson** [comment]
确保使用的是最新的 API，或许是网络问题也说不定

我这边测试是正常的
![](https://upload.cc/i1/2020/07/26/xB4Rab.png)

**Comment by rachpt** [comment]
看cmd截图，应该是
https://github.com/zaxtyson/LanZouCloud-API/blob/b0644356d1e7e8c9c753d5a255c335cb3a2c02aa/lanzou/api/core.py#L1017
这一行的没有拿到数据得到的 None 直接进行 json 解析导致的闪退。
这种网络请求得不到数据还是比较常见的 https://github.com/Aruelius/cloud189/issues/39

**Comment by zaxtyson** [comment]
是的，所以说可能是网络问题，但是几乎没碰到过这个情况

**Comment by XM12G** [comment]
![QQ图片20200726204107](https://user-images.githubusercontent.com/35884945/88479254-5827fa80-cf80-11ea-8f94-9c994ffc0328.png)
的却是网络问题
现在升级后不报那个错了，换了个报错

**Comment by zaxtyson** [comment]
能分享一下下载部分的代码嘛，json解析错误还是头一次出现

**Comment by XM12G** [comment]
依旧是down_dir_by_url方法的问题呀
那个代码压根儿没改
只是换成了从网络上获取url罢了
（url是绝对正确的）
