### ISSUE TITLE
同名文件下载，会追加而不是覆盖

### ISSUE THREAD

**Issue by zhbzhbzhbz** [zaxtyson/LanZouCloud-API#35]
就我突然想到，
比如我本地有一个1.txt，然后里面输入一大堆文字
我发现调用下载功能下载另一个1.txt的时候，从callback看，是追加的写入，而没有覆盖
并且确认了下，下载“完成”的文件里，开头的部分还是原来的文件内容

另外，是否可以给错误码加一个，“文件已下载过”？

我是遇到这么个需求哈：
我在下载文件，通过之前说的callback来获取文件名。但是如果这个文件已经下载过，callback哪怕一次都不会触发，这样的话我就无从获得文件名（之前提到过，用另一个api来解析文件名有额外的时间开销）

**Comment by zaxtyson** [comment]
因为API支持断点续传，再一次下载同名文件，且比之前的文件大，就会认为本地文件是未下载完成的，于是自动续传了。

**Comment by zhbzhbzhbz** [comment]
> 因为API支持断点续传，再一次下载同名文件，且比之前的文件大，就会认为本地文件是未下载完成的，于是自动续传了。

1）"支持下载续传，大文件未下载完成时通过 filename.record 文件记录进度，下载完成自动删除" 
不过如果没有这个文件的时候，好像也会断点续传？
2）"下载完成后，重复下载不会覆盖文件，直接返回状态码 SUCCESS"
是否考虑加一个force_overwrite的选项允许强制覆盖？~

**Comment by zaxtyson** [comment]
大文件的续传和普通文件续传是两套机制，普通文件续传出现这种bug是之前没想到的，正在改~

**Comment by zhbzhbzhbz** [comment]
> 大文件的续传和普通文件续传是两套机制，普通文件续传出现这种bug是之前没想到的，正在改~

哦哦辛苦了~

**Comment by zaxtyson** [comment]
可以了，下载完成的回调也顺带加上去了，试试看😁

**Comment by zhbzhbzhbz** [comment]
> 可以了，下载完成的回调也顺带加上去了，试试看😁

感谢~好用~尤其这个overwrite参数非常有灵性，一加上解决好多问题
