### ISSUE TITLE
登录不了

### ISSUE THREAD

**Issue by yiyexingyu** [zaxtyson/LanZouCloud-API#41]
现在登录不了了，需要滑动验证。怎么办？

**Comment by zaxtyson** [comment]
请使用cookie登录

见 https://github.com/zaxtyson/LanZouCloud-API/wiki/0x02-%E7%99%BB%E5%BD%95%E5%92%8C%E6%B3%A8%E9%94%80#login_by_cookiecookie

**Comment by yiyexingyu** [comment]
> 请使用cookie登录
> 
> 见 https://github.com/zaxtyson/LanZouCloud-API/wiki/0x02-%E7%99%BB%E5%BD%95%E5%92%8C%E6%B3%A8%E9%94%80#login_by_cookiecookie

已经解决。thanks！
