### ISSUE TITLE
post中www.的前缀部分机器会拦截

### ISSUE THREAD

**Issue by wxh0402** [zaxtyson/LanZouCloud-API#44]
core.py中
self._host_url = 'https://www.lanzous.com'和'Referer': 'https://www.lanzous.com',
在部分网络运营商和机器上，www会被拦截，改成wws或者pan就好了

**Comment by zaxtyson** [comment]
这么神奇的嘛😦, 之前有个兄弟, 本机上面跑不了, 本机开虚拟机可以跑.

我看了 www 和 pan 解析的 IP 的确不一样

但是同一台设备, 出口 IP 应该是一致的, 虚拟机正常, 物理机机被拦截. 

如果可以的话, 试一下虚拟机, 网络环境这个问题我这边很难复现, 确认是这个原因的话, 就得改成 pan 了

**Comment by wxh0402** [comment]
测试了一下 用的是window10自带的沙盒
还是www无法访问 pan可以~

**Comment by slgluo** [comment]
@zaxtyson 这么问题有思路了吗，我调试也发现这个问题了

**Comment by zaxtyson** [comment]
ook~~

**Comment by wxh0402** [comment]
utils.py 中还有一个header 会在解析触发

**Comment by zaxtyson** [comment]
ok 了

**Comment by wxh0402** [comment]
HHH 好了~麻烦你了~
