### ISSUE TITLE
ModuleNotFoundError: No module named 'lanzou.api';

### ISSUE THREAD

**Issue by PerpEternal** [zaxtyson/LanZouCloud-API#45]
执行
`from lanzou.api import LanZouCloud`
报错
`ModuleNotFoundError: No module named 'lanzou.api'; 'lanzou' is not a package`

**Comment by zaxtyson** [comment]
在 IDE, CMD下导入似乎都没有问题
![image](https://user-images.githubusercontent.com/20383074/103334223-91bedd80-4aab-11eb-967f-25d996fc5185.png)

或许是文件权限的问题

**Comment by PerpEternal** [comment]
我把文件命名为 lanzou.py，和包名重复了，蠢哭了😂

**Comment by zaxtyson** [comment]
红红火火恍恍惚惚
