### ISSUE TITLE
request.get在部分的电脑上出现 无法请求出去的情况

### ISSUE THREAD

**Issue by wxh0402** [zaxtyson/LanZouCloud-API#54]
python的request.get 在部分的电脑上出现 无法请求出去的情况
不加timeout 会一直挂起在那 但是网页又能访问 不是dns的问题
要不要request那边用_timeout的超时时间

**Comment by zaxtyson** [comment]
设置了 timeout 的, 默认是 15 s, **无法发出请求**这种情况还没碰到过, 是不是后台开了 VPN 代理软件, 有时会出现一些问题

**Comment by wxh0402** [comment]
我也觉得很奇妙 上次远程朋友的电脑
百度都没法request出去，浏览器访问都是正常访问
