### ISSUE TITLE
上传后-1报错

### ISSUE THREAD

**Issue by zsbai** [zaxtyson/LanZouCloud-API#57]
上传文件加了进度条，发现进度条走完后报错-1，看了错误码不知道一般错误是啥意思.....

**Comment by zsbai** [comment]
换了台服务器也是一样的报错，第一个文件为130m的dmg和400m的mp4均报错

**Comment by zaxtyson** [comment]
似乎没有问题

```
lzy = LanZouCloud()
lzy.ignore_limits()   # 上传大文件先解除官方限制
```

![image](https://user-images.githubusercontent.com/20383074/117557335-4c876980-b0a4-11eb-8fe3-9974adcd86eb.png)

![image](https://user-images.githubusercontent.com/20383074/117557379-d6cfcd80-b0a4-11eb-9ef6-e516b88cca38.png)

![image](https://user-images.githubusercontent.com/20383074/117557382-e9e29d80-b0a4-11eb-8bc7-5a898058c0e6.png)

![image](https://user-images.githubusercontent.com/20383074/117557553-70e44580-b0a6-11eb-921d-6c0b708ac15e.png)

**Comment by zsbai** [comment]
奥不好意思，我同时加了lzy.set_max_size(500)和lzy.ignore_limits()上传好像就会报错....把第一个删掉就成了，感谢

**Comment by zaxtyson** [comment]
`set_max_size() ` 是给蓝奏云 VIP 用户使用的, `max_size` 是指单个文件的最大大小, 普通用户是 100MB, 不同的会员等级, 单文件大小上限不同. 

当上传的单文件小于 `max_size` 时会直接上传, 当文件超过限制时, API 会把文件拆分成块上传.

**Comment by zsbai** [comment]
懂了，感谢
