### ISSUE TITLE
timeout 无效

### ISSUE THREAD

**Issue by rachpt** [zaxtyson/LanZouCloud-API#7]
https://github.com/zaxtyson/LanZouCloud-API/blob/89f4d3e00d2cbf51cd7e8c64dfad9bf499923b49/lanzou/api.py#L44

requests 里面的 timeout 单位应该是秒， https://stackoverflow.com/a/54619932
这样的话 同时需要为上传文件单独定义一个 timeout 更大的 post函数，或者 timeout使用tuples，https://codeigo.com/python/requests-timeout

**Comment by zaxtyson** [comment]
的确是搞错单位了，https://cn.python-requests.org/zh_CN/latest/user/advanced.html#timeout,马上改👌

**Comment by zaxtyson** [comment]
https://github.com/zaxtyson/LanZouCloud-CMD/issues/9#issuecomment-586326309
会员用户分卷可以设置为 260 MB，上传超时 3600s 应该够了，也就是平均网速达到 74kb/s 的样子，时间太长估计用户也会强行终止。

**Comment by zaxtyson** [comment]
已经在 `dev` 分支中修复😁
