### ISSUE TITLE
Android api应该怎么调用呢

### ISSUE THREAD

**Issue by dabai2017** [zaxtyson/LanZouCloud-API#8]
我看了看wiki只有py的

**Comment by zaxtyson** [comment]
是的，这是 Python3 实现的。虽然说 Java 也可以调用 Python 的接口，但是还是要 Python 的环境，Android 那应该没办法适配，或许耗费的精力比用 Java 重写 API 还多😜。代码都有注释，可以看看思路，网盘的接口、参数都摸索好了，试试用 Java 实现一次。其实我也想做一个 APP 的，可惜对 Android 不是很了解~

**Comment by dabai2017** [comment]
哈哈今天我看了你的py源码，大概理解点了。知道从哪开始post了  有时间我研究研究Java方面
