### ISSUE TITLE
上传文件，名称被截断了

### ISSUE THREAD

**Issue by Koloz** [zaxtyson/LanZouCloud-API#90]
调用.upload_file(file_path, folder_id, *, callback, uploaded_handler) 上传文件到网盘

`本地文件名：2020_《工业企业的数字化转型》_IBM.pdf`
`上传后显示：2020_《工..._lan.pdf`

**Comment by Baxy0** [comment]
+1

**Comment by wxh0402** [comment]
https://pc.woozooo.com/fileup.php
改成
https://pc.woozooo.com/html5up.php

**Comment by Baxy0** [comment]
> https://pc.woozooo.com/fileup.php
> 改成
> https://pc.woozooo.com/html5up.php
>  

按照你说的问题解决了！感谢！

**Comment by Koloz** [comment]
感谢，问题按照上述方法已解决
